//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public string MartialStatus { get; set; }
        public bool Employed { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Birthplace { get; set; }
    }
}
